name: Trigger Netlify to build docs
on:
  push:
    branches:
      - '1.x'
    paths:
      - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TOKEN: ${{ secrets.NETLIFY_BUILD_HOOK }}
      TRIGGER_TITLE: ${{ format('Triggered by {0} source repo', github.repository) }}
      TRIGGER_BRANCH: ${{ github.ref_name }}
    steps:
      - name: Trigger Netlify Build Hook
        if: env.TOKEN != ''
        run: curl -s -X POST -d {} "https://api.netlify.com/build_hooks/${TOKEN}?trigger_branch=${TRIGGER_BRANCH}&trigger_title=${TRIGGER_TITLE}"